### ISSUE TITLE
[error]Cannot read property 'author' of undefined

### ISSUE THREAD

**Issue by Andre601** [rjstone/discord-webhook-notify#2]
When executing the job below, does the workflow fail with this error.
```
##[error]Cannot read property 'author' of undefined
##[error]Node run failed with exit code 1
```

Workflow:
```yaml
name: Publication task

on:
  release:
    types: [published]
    branches:
    - master

jobs:
  publish:
    # Unrelated task that runs successfully, allowing below task to start.
  sendMessage:
    needs: [publish]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: rjstone/discord-webhook-notify@v1.0.2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: info
        avatarUrl: 'https://raw.githubusercontent.com/botblock/JavaBotBlockAPI/master/src/main/resources/jbba.png'
        username: New release (${{ github.event.release.tag_name }})
        text: ${{ github.event.release.name }}
        description: '**Release Information**'
        details: '${{ github.event.release.body }}'
```
