### ISSUE TITLE
Action fails with SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by marcft** [rjstone/discord-webhook-notify#22]
I’m using the `rjstone/discord-webhook-notify@v1` action in my GitHub Actions workflow, but the action is failing with the following error message:  

```plaintext
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at D:\a\_actions\rjstone\discord-webhook-notify\v1\node_modules\webhook-discord\lib\webhook.js:22:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
```

However, when I use `curl` to send the same webhook request, it works perfectly fine. This indicates that the problem may lie within the action itself, as Discord responds correctly to a `curl` request of the exact same webhook url.

---

### **Steps to Reproduce:**  
1. I used the following GitHub Action workflow:  

```yaml
name: Test notify issue pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: 'info'
          text: 'A new version of code deployed successfully'

      - name: Debug Webhook Response
        if: always()
        run: |
          curl -i -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d '{"content":"Test message from GitHub Actions for issue"}'
```

2. The **`Notify Discord`** step fails with the error message seen before.

3. The **`curl`** step works fine and sends the webhook request successfully to Discord.

---

### **Expected Behavior:**  
The `rjstone/discord-webhook-notify` action should send the webhook successfully, similar to the manual `curl` command.

---

### **Actual Behavior:**  
The `rjstone/discord-webhook-notify` action fails with the error message seen before, the complete GitHub Actions log is the following:

```plaintext
Run rjstone/discord-webhook-notify@v1
  with:
    webhookUrl: ***
    severity: info
    text: A new version of code deployed successfully

      A new version of code deployed successfully
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at /home/runner/work/_actions/rjstone/discord-webhook-notify/v1/node_modules/webhook-discord/lib/webhook.js:22:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
```

However, the `curl` command works and successfully sends a message to Discord.

---

### **Additional Info:**  
- **GitHub Actions Runner:** `ubuntu-latest`
- **Node.js version:** `20.18.0`
- **Webhook works fine manually using curl**
- **Tried running on Windows?** Yes, windows-latest also doesn't work for me.

---

### **Temporary Workaround:**  
Since the action is not working as expected, I’m currently using the following workaround to send the webhook using `curl`:

```yaml
- name: Notify Discord (Temporary Fix)
  run: |
    curl -X POST -H "Content-Type: application/json" \
    -d '{"username": "GitHub Bot", "content": "✅ Deployment successful!"}' \
    "${{ secrets.DISCORD_WEBHOOK }}"
```

It's not as easy to use as the action, but that should do the job. You could also try with another action.

---

### **Request:**  
Please investigate why the action fails with the `SyntaxError` and provide a fix or an alternative solution.

---

Feel free to copy-paste this directly into a new issue on the repository. Let me know if you'd like any modifications! 😊
