### ISSUE TITLE
Crash when running scheduled job

### ISSUE THREAD

**Issue by marknuzz** [rjstone/discord-webhook-notify#9]
This line throws because payload.repository is nil. the only key within 'payload' is 'schedule'. eventName is 'schedule'.
https://github.com/rjstone/discord-webhook-notify/blob/89b0bf43c2c8514f70d0dcba4a706b904e8a3112/index.js#L48
```
name: Test Failure

on:
  schedule:
    # Every day 1 hours
    - cron: '0 */1 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Report Success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Smoke Test Successful
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

```
